"""
USE CASE: This playbook will perform triage tasks, identify false positive; else perform enrichment,
containment and notification
"""

import phantom.rules as phantom
import json
from datetime import datetime, timedelta
@phantom.playbook_block()
def on_start(container):
    phantom.debug('on_start() called')
    
    # call 'playbook_local_KTB_Triage_Playbook_for_inbound_1' block
    playbook_local_KTB_Triage_Playbook_for_inbound_1(container=container)

    return

"""
If similar
events found
in last 7 days
and are false
positive
"""
@phantom.playbook_block()
def if_similar_events_found_in_last_7_days_a(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('if_similar_events_found_in_last_7_days_a() called')
    
    status_param = container.get('status', None)

    # check for 'if' condition 1
    matched = phantom.decision(
        container=container,
        action_results=results,
        conditions=[
            [status_param, "==", "closed"],
        ])

    # call connected blocks if condition 1 matched
    if matched:
        return

    # call connected blocks for 'else' condition 2
    set_status_to_in_progress(action=action, success=success, container=container, results=results, handle=handle, custom_function=custom_function)

    return

"""
If
event is
generated by
AMP /
Kaspersky /
McAfee
"""
@phantom.playbook_block()
def If_event_is_generated_by_AMP_Kaspersky(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('If_event_is_generated_by_AMP_Kaspersky() called')

    # check for 'if' condition 1
    matched = phantom.decision(
        container=container,
        action_results=results,
        conditions=[
            ["artifact:*.cef.sourceAddress", "!=", ""],
        ])

    # call connected blocks if condition 1 matched
    if matched:
        format_data_ro_query(action=action, success=success, container=container, results=results, handle=handle, custom_function=custom_function)
        return

    return

"""
Call Enrich Playbook
"""
@phantom.playbook_block()
def call_enrich_playbook(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('call_enrich_playbook() called')
    
    # call playbook "local/KTB - Enrich Playbook", returns the playbook_run_id
    playbook_run_id = phantom.playbook(playbook="local/KTB - Enrich Playbook", container=container, name="call_enrich_playbook", callback=ioc_is_suspicious)

    return

"""
IOC is
suspicious
"""
@phantom.playbook_block()
def ioc_is_suspicious(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('ioc_is_suspicious() called')

    # check for 'if' condition 1
    matched = phantom.decision(
        container=container,
        action_results=results,
        conditions=[
            ["Query_stats_total_count_for_last_1hour:action_result.data.*.count", ">=", 1000],
            ["artifact:*.cef.sourceAddres_malicious", "==", True],
        ],
        logical_operator='and')

    # call connected blocks if condition 1 matched
    if matched:
        return

    # call connected blocks for 'else' condition 2

    return

"""
Call Contain
Playbook
"""
@phantom.playbook_block()
def call_contain_playbook(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('call_contain_playbook() called')
    
    # call playbook "local/KTB - UC1 Malware - Contain Playbook_with _Internal-Contain", returns the playbook_run_id
    playbook_run_id = phantom.playbook(playbook="local/KTB - UC1 Malware - Contain Playbook_with _Internal-Contain", container=container, name="call_contain_playbook")

    return

@phantom.playbook_block()
def set_status_to_in_progress(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('set_status_to_in_progress() called')

    phantom.set_status(container=container, status="In progress")
    promote_to_case_6(container=container)

    return

@phantom.playbook_block()
def promote_to_case_6(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('promote_to_case_6() called')

    phantom.promote(container=container, template="KTB Workbook")
    If_event_is_generated_by_AMP_Kaspersky(container=container)
    playbook_local_ktb_uc_send_email_case_promotion_1(container=container)

    return

@phantom.playbook_block()
def playbook_local_ktb_uc_send_email_case_promotion_1(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('playbook_local_ktb_uc_send_email_case_promotion_1() called')
    
    # call playbook "local/KTB UC SEND EMAIL CASE PROMOTION", returns the playbook_run_id
    playbook_run_id = phantom.playbook(playbook="local/KTB UC SEND EMAIL CASE PROMOTION", container=container)

    return

@phantom.playbook_block()
def playbook_local_KTB_Triage_Playbook_for_inbound_1(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('playbook_local_KTB_Triage_Playbook_for_inbound_1() called')
    
    # call playbook "local/KTB -Triage Playbook for inbound", returns the playbook_run_id
    playbook_run_id = phantom.playbook(playbook="local/KTB -Triage Playbook for inbound", container=container, name="playbook_local_KTB_Triage_Playbook_for_inbound_1", callback=if_similar_events_found_in_last_7_days_a)

    return

@phantom.playbook_block()
def format_data_ro_query(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('format_data_ro_query() called')
    
    template = """summariesonly=true allow_old_summaries=true max(_time) AS lastTime count FROM datamodel=Network_Traffic where (sourcetype=fortigate_traffic OR sourcetype=pan:traffic) AND All_Traffic.src_ip={0} AND (earliest=-4h@h latest=now) by  _time span=1h sourcetype All_Traffic.action 
| rename \"All_Traffic.*\" as \"*\""""

    # parameter list for template variable replacement
    parameters = [
        "artifact:*.cef.sourceAddress",
    ]

    phantom.format(container=container, template=template, parameters=parameters, name="format_data_ro_query", separator=", ")

    Query_stats_by_sourcetype(container=container)

    return

@phantom.playbook_block()
def Query_stats_by_sourcetype(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('Query_stats_by_sourcetype() called')
        
    #phantom.debug('Action: {0} {1}'.format(action['name'], ('SUCCEEDED' if success else 'FAILED')))
    
    # collect data for 'Query_stats_by_sourcetype' call
    formatted_data_1 = phantom.get_format_data(name='format_data_ro_query')

    parameters = []
    
    # build parameters list for 'Query_stats_by_sourcetype' call
    parameters.append({
        'query': formatted_data_1,
        'command': "tstats",
        'display': "",
        'parse_only': "",
    })

    phantom.act(action="run query", parameters=parameters, assets=['splunk es asset'], callback=format_data_to_query_total_count, name="Query_stats_by_sourcetype")

    return

@phantom.playbook_block()
def format_data_to_query_total_count(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('format_data_to_query_total_count() called')
    
    template = """summariesonly=true allow_old_summaries=true count FROM datamodel=Network_Traffic where (sourcetype=fortigate_traffic OR sourcetype=pan:traffic) AND All_Traffic.src_ip={0} earliest=-4h@h latest=now
| rename \"All_Traffic.*\" as \"*\""""

    # parameter list for template variable replacement
    parameters = [
        "artifact:*.cef.sourceAddress",
    ]

    phantom.format(container=container, template=template, parameters=parameters, name="format_data_to_query_total_count", separator=", ")

    Query_stats_total_count_for_last_1hour(container=container)

    return

@phantom.playbook_block()
def Query_stats_total_count_for_last_1hour(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('Query_stats_total_count_for_last_1hour() called')
        
    #phantom.debug('Action: {0} {1}'.format(action['name'], ('SUCCEEDED' if success else 'FAILED')))
    
    # collect data for 'Query_stats_total_count_for_last_1hour' call
    formatted_data_1 = phantom.get_format_data(name='format_data_to_query_total_count')

    parameters = []
    
    # build parameters list for 'Query_stats_total_count_for_last_1hour' call
    parameters.append({
        'query': formatted_data_1,
        'command': "tstats",
        'display': "",
        'parse_only': "",
    })

    phantom.act(action="run query", parameters=parameters, assets=['splunk es asset'], callback=tstats_query_total_numver, name="Query_stats_total_count_for_last_1hour")

    return

@phantom.playbook_block()
def tstats_query_total_numver(action=None, success=None, container=None, results=None, handle=None, filtered_artifacts=None, filtered_results=None, custom_function=None, **kwargs):
    phantom.debug('tstats_query_total_numver() called')

    results_data_1 = phantom.collect2(container=container, datapath=['Query_stats_total_count_for_last_1hour:action_result.data.*.count'], action_results=results)

    results_item_1_0 = [item[0] for item in results_data_1]

    note_title = "Total count of  tstats run query"
    note_content = results_item_1_0
    note_format = "markdown"
    phantom.add_note(container=container, note_type="general", title=note_title, content=note_content, note_format=note_format)
    call_enrich_playbook(container=container)

    return

@phantom.playbook_block()
def on_finish(container, summary):
    phantom.debug('on_finish() called')
    # This function is called after all actions are completed.
    # summary of all the action and/or all details of actions
    # can be collected here.

    # summary_json = phantom.get_summary()
    # if 'result' in summary_json:
        # for action_result in summary_json['result']:
            # if 'action_run_id' in action_result:
                # action_results = phantom.get_action_results(action_run_id=action_result['action_run_id'], result_data=False, flatten=False)
                # phantom.debug(action_results)

    return